### ISSUE TITLE
[v8] Compiling script with error causing the delegate node crash

### ISSUE THREAD

**Issue by HackFisher** [bitsuperlab/bitshares_play#116]
```
[delegate] request: wallet_delegate_set_block_production ALL true


encountered EOFError, delegate instance may have crashed
waiting for process 45911 to exit
/usr/local/Cellar/ruby/2.1.3_1/lib/ruby/2.1.0/net/protocol.rb:153:in `read_nonblock': end of file reached (EOFError)
	from /usr/local/Cellar/ruby/2.1.3_1/lib/ruby/2.1.0/net/protocol.rb:153:in `rbuf_fill'
	from /usr/local/Cellar/ruby/2.1.3_1/lib/ruby/2.1.0/net/protocol.rb:134:in `readuntil'
	from /usr/local/Cellar/ruby/2.1.3_1/lib/ruby/2.1.0/net/protocol.rb:144:in `readline'
	from /usr/local/Cellar/ruby/2.1.3_1/lib/ruby/2.1.0/net/http/response.rb:39:in `read_status_line'
	from /usr/local/Cellar/ruby/2.1.3_1/lib/ruby/2.1.0/net/http/response.rb:28:in `read_new'
	from /usr/local/Cellar/ruby/2.1.3_1/lib/ruby/2.1.0/net/http.rb:1408:in `block in transport_request'
	from /usr/local/Cellar/ruby/2.1.3_1/lib/ruby/2.1.0/net/http.rb:1405:in `catch'
	from /usr/local/Cellar/ruby/2.1.3_1/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'
	from /usr/local/Cellar/ruby/2.1.3_1/lib/ruby/2.1.0/net/http.rb:1378:in `request'
	from /Users/fisher/superlab/bitshares_play/tests/bdd_tests/bitshares_api.rb:78:in `block in request'
	from /usr/local/Cellar/ruby/2.1.3_1/lib/ruby/2.1.0/net/http.rb:853:in `start'
	from /usr/local/Cellar/ruby/2.1.3_1/lib/ruby/2.1.0/net/http.rb:583:in `start'
	from /Users/fisher/superlab/bitshares_play/tests/bdd_tests/bitshares_api.rb:76:in `request'
	from /Users/fisher/superlab/bitshares_play/tests/bdd_tests/client.rb:95:in `exec'
	from ./testnet.rb:135:in `start'
	from ./testnet.rb:233:in `<main>'
```

**Comment by HackFisher** [comment]
https://github.com/bitsuperlab/bitshares_play/blob/v8/libraries/game/v8_game.cpp#L64

**Comment by clar** [comment]
this is because delegate by default doesn't do block scanning, so game script is not downloaded

**Comment by clar** [comment]
one workaround is to set scanning flag to true temporaraily

**Comment by HackFisher** [comment]
@clar The issue you mentioned has already been addressed in commit https://github.com/bitsuperlab/bitshares_play/commit/1a35a88358c9d6d902f63cd2802bd4b2886ed069

The script downloading/claiming now is in the create_game_operation evaluate.

**Comment by HackFisher** [comment]
https://developers.google.com/v8/embed#exceptions

**Comment by clar** [comment]
I debugged yesterday， looks like the complied java script is empty

**Comment by HackFisher** [comment]
@clar ok, I guess so, it might due to the syntax error of the javascript.
what does the GetIsolate()->ThrowException used for?
```
GetIsolate()->ThrowException( v8::String::NewFromUtf8(GetIsolate(), "Error loading file" ) );
```

**Comment by HackFisher** [comment]
https://github.com/bitsuperlab/bitshares_play/commit/83b3d856fb95e6d936eb0c3a800d9bd65cfe110d
