### ISSUE TITLE
[v8][test] bdd_tests localhost server connection refused for unknown reason when enter interactive mode

### ISSUE THREAD

**Issue by HackFisher** [bitsuperlab/bitshares_play#120]
```
node delegate is up
node bob is up
node mail is up
Error: node alice is down
Error: node alice is down
[delegate] request: wallet_open default
ok
[delegate] request: wallet_unlock 9999999 password
ok
[delegate] request: wallet_delegate_set_block_production ALL true
ok
[alice] request: wallet_open default
ok
[alice] request: wallet_unlock 9999999 password
ok
[bob] request: wallet_open default
ok
[bob] request: wallet_unlock 9999999 password
ok
[alice] request: execute_command_line enable_raw
ok
[bob] request: execute_command_line enable_raw
ok
[mail] request: execute_command_line enable_raw
ok
@pause: use the following urls to access the nodes via browser:
- delegate node: http://localhost:5690
- alice node: http://localhost:5691
- bob node: http://localhost:5692
or press [d],[a], [b], or [m] to have console access
or press any other key to shutdown testnet and continue..

entering node 'delegate' interactive mode, enter 'exit' or 'quit' to exit
/usr/local/Cellar/ruby/2.1.3_1/lib/ruby/2.1.0/net/http.rb:879:in `initialize': Connection refused - connect(2) for "localhost" port 5690 (Errno::ECONNREFUSED)
	from /usr/local/Cellar/ruby/2.1.3_1/lib/ruby/2.1.0/net/http.rb:879:in `open'
	from /usr/local/Cellar/ruby/2.1.3_1/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
	from /usr/local/Cellar/ruby/2.1.3_1/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
	from /usr/local/Cellar/ruby/2.1.3_1/lib/ruby/2.1.0/net/http.rb:878:in `connect'
	from /usr/local/Cellar/ruby/2.1.3_1/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
	from /usr/local/Cellar/ruby/2.1.3_1/lib/ruby/2.1.0/net/http.rb:852:in `start'
	from /usr/local/Cellar/ruby/2.1.3_1/lib/ruby/2.1.0/net/http.rb:583:in `start'
	from /Users/fisher/superlab/bitshares_play/tests/bdd_tests/bitshares_api.rb:76:in `request'
	from /Users/fisher/superlab/bitshares_play/tests/bdd_tests/client.rb:140:in `interactive_mode'
	from ./testnet.rb:211:in `pause'
	from ./testnet.rb:235:in `<main>'
```

But it is normal when setup the network manually instead of run 
```
./testnet.rb
```

**Comment by HackFisher** [comment]
no further reproducible now
