### ISSUE TITLE
[v8][test] alice crash unexpectedly when testing, due to downloading script?

### ISSUE THREAD

**Issue by HackFisher** [bitsuperlab/bitshares_play#122]
```
first time test net bootstrap.. this may take several minutes, please be patient..
    Given I'm Alice                                                                                                       # features/step_definitions/basic_wallet_steps.rb:7
    And I received 5200000 XTS from angel                                                                                 # features/step_definitions/basic_wallet_steps.rb:43
    And I wait for one block                                                                                              # features/step_definitions/basic_wallet_steps.rb:68
    And I print XTS balance                                                                                               # features/step_definitions/basic_wallet_steps.rb:76
      balance: 5200000.0 XTS
encountered EOFError, alice instance may have crashed
waiting for process 68597 to exit
    And I created a game called dice                                                                                      # features/step_definitions/game_steps.rb:7
      alice (pid:68597) instance was crashed or exited unexpectedly (BitSharesNode::Error)
      ./client.rb:103:in `rescue in rescue in exec'
      ./client.rb:100:in `rescue in exec'
      ./client.rb:94:in `exec'
      ./features/step_definitions/game_steps.rb:10:in `/^I created a game called (\w+)$/'
      features/play_dice.feature:12:in `And I created a game called dice'
    And I wait for one block                                                                                              # features/step_definitions/basic_wallet_steps.rb:68
    And I created a game asset called DICE for dice with precision 0.01, initial supply 10000, and inital collateral 1000 # features/step_definitions/game_steps.rb:1
    And I wait for one block                                                                                              # features/step_definitions/basic_wallet_steps.rb:68
shutting down testnet..
      Broken pipe (Errno::EPIPE)
      /Users/fisher/superlab/bitshares_play/tests/bdd_tests/client.rb:71:in `write'
      /Users/fisher/superlab/bitshares_play/tests/bdd_tests/client.rb:71:in `stop'
      /Users/fisher/superlab/bitshares_play/tests/bdd_tests/testnet.rb:184:in `shutdown'
      /Users/fisher/superlab/bitshares_play/tests/bdd_tests/features/support/env.rb:154:in `After'
```

**Comment by HackFisher** [comment]
```
015-05-07T10:05:20 th_a:http_server handle_connection store_pending_transa ] storing new local transaction with id 9b7c3a6a5a13f17fd317efe899b4df4478631036         chain_database.cpp:2190
 68 2015-05-07T10:05:20 th_a:http_server handle_connection script_http_callback ] The url is http://www.dacsunlimited.com/games/dice.js, the hash is 000        client.cpp:141
 69 2015-05-07T10:05:20 th_a:http_server handle_connection                 init ] The path is tmp/alice/game_client/dice.js       v8_game.cpp:54
 70 2015-05-07T10:05:20 th_a:http_server handle_connection                 init ] The souce is Empty, error loading file       v8_game.cpp:59
```

store pending transaction
-> evaluate transaction
-> evaluate operation
-> .. -->async downloading script
-> init game engine

the script is not downloaded yet

**Comment by HackFisher** [comment]
And what if the connection to the url is break? Then the block syncing (or pending transaction validation) need to stop util this file get downloaded/compiled/runnable.

This do not have enough level of stability, we should support a way the blockchain can still goon without some of the games execution. (At least for normal full nodes, they do not need to check in script_unposition status)

**Comment by HackFisher** [comment]
Get not to crash, after using Isolate::ThrowException
```
2015-05-07T10:13:00 th_a:http_server handle_connection                 init ] The souce is Empty, error loading file       v8_game.cpp:59
 68 2015-05-07T10:13:00 th_a:http_server handle_connection init_game_engine_if_ ] game engine register failed: 100010 failed_loading_source_file: failed to compile script
 69
 70     {"script_path":"tmp/alice/game_client/dice.js","*error":"Error loading file"}
 71     th_a  v8_game.cpp:62 init       client.cpp:132
 72 2015-05-07T10:13:00 th_a:http_server handle_connection             evaluate ] game engine note found, failed to init for unknown reason during evaluate operation       game_operations.cpp:55
```

And The execute get passed unexpectedly for unknown reason. The result is the function definition
```
2015-05-07T10:13:13 th_a:invoke handle_message                 init ] The result of the running of script is function ( rule, wallet_transaction_record, wallet )
 85 {
 86     // TODO: Accessor to type, (withdraw_condition_types)
 87     // TODO: Define withdraw type constants
 88     switch( rule.condition.type )
 89     {
 90         case withdraw_null_type:
 91         {
 92             // TODO
 93             // FC_THROW( "withdraw_null_type not implemented!" );
 94             break;
 95         }
 96         case withdraw_signature_type:
 97         {
 98             // TODO: auto condtion = rule.condition.as<withdraw_with_signature>();
 99             // TODO: lookup if cached key and work with it only
100             // if( _wallet_db.has_private_key( deposit.owner ) )
101             if( rule.condtion.memo )
102             {
103                 // TODO: TITAN, FC_THROW( "withdraw_option_type not implemented!" );
104                 break;
```

**Comment by HackFisher** [comment]
Now we store code on chain instead of url
